categories:
  SkipToContent:
    label: 'Skip to content'
  SkipToContent.target:
    label: 'Targets'
    parent: SkipToContent

settings:
  SkipToContent.target.skipToContent:
    label: 'HTML Anchor to your main content'
    description: 'This value is used inside href of a link'
    category: SkipToContent.target
    type: string
    default: '#pageContent'
  SkipToContent.target.skipToFooter:
    label: 'HTML Anchor to your page footer'
    description: 'This value is used inside href of a link'
    category: SkipToContent.target
    type: string
    default: '#pageFooter'
  SkipToContent.mode:
    label: 'Mode'
    description: 'Mode: js ignores CSS selectors and detects the header and footer landmark automatically. Use it, if you landmarks dont have IDs'
    category: SkipToContent.mode
    type: string
    default: 'css'
    enum:
      css: 'css'
      js: 'js (not recommended)'
  SkipToContent.autoInclude:
    label: 'Auto include'
    description: 'If enables, then the skip to content links are set automatically inside your page object. Only works, if FLUIDTEMPLATE is on position page.10'
    type: bool
    default: false
